CREATE USER KEPFELDOLGOZAS_ADMIN
IDENTIFIED BY 12345678
DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON users;
  
GRANT CREATE SESSION TO KEPFELDOLGOZAS_ADMIN;
GRANT CREATE TABLE TO KEPFELDOLGOZAS_ADMIN;
GRANT CREATE VIEW TO KEPFELDOLGOZAS_ADMIN;
GRANT CREATE SEQUENCE TO KEPFELDOLGOZAS_ADMIN;
GRANT CREATE TRIGGER TO KEPFELDOLGOZAS_ADMIN;
GRANT CREATE PROCEDURE TO KEPFELDOLGOZAS_ADMIN;
GRANT CREATE TYPE TO KEPFELDOLGOZAS_ADMIN;
